### ISSUE TITLE
[bug] `tokens.at` is not a function

### ISSUE THREAD

**Issue by gorner** [markedjs/marked#3546]
**Marked version:**
15.0.2

**Describe the bug**
After upgrading from v14, our app started getting error reports with the following text:

```
t.at is not a function. (In 't.at(-1)', 't.at' is undefined)
Please report this to https://github.com/markedjs/marked.
```

... so I am doing as instructed 😛 

The immediate stack trace reads:

```
assets/node_modules/marked/lib/marked.umd.js:1522:0:in `at'
```

```js
                }
                if (this.state.top && (token = this.tokenizer.paragraph(cutSrc))) {
                    const lastToken = tokens.at(-1);
                    if (lastParagraphClipped && lastToken?.type === 'paragraph') {
                        lastToken.raw += '\n' + token.raw;
```

**To Reproduce**
Unclear as this only arose through our error logging. We ended up rolling back the `marked` upgrade, but if/when we find out more information about a specific reproduction path, we will update.

However our logging indicates this error only occurs on a limited range of older browser versions, including Safari 15.3 and earlier, and Chrome 125 and earlier, and it [appears](https://caniuse.com/mdn-javascript_builtins_array_at) the `.at()` method is not supported on Safari before v15.4 (though supposedly it's supported in Chrome 92+ making the error there a bit more curious). It's not clear whether Marked still supports these versions as the readme currently only says "not IE11".

**Expected behavior**
The parsing works as expected / without error.

**Comment by UziTech** [comment]
We don't officially support any browsers but we support nodejs >=18 which I believe is es2022 so any browsers that support es2022 should work.

If you need support for older browsers using babel to transpile marked to your target browsers should work. If it doesn't, feel free to create an issue for that.

**Comment by gorner** [comment]
@UziTech Thanks for the reply. For the record we currently have `safari > 14.1.2, chrome > 57` specified in our .browserslistrc (which [should be used by Babel](https://browsersl.ist)) so if this was something Babel would catch/transpile it should have done so. It [doesn't appear](https://stackoverflow.com/a/55420761/1927191) Babel transpilation handles changes in syntax like this in and of itself, but we could set up a polyfill (with additional packages and config). Or we could just update our browser targets.

Ultimately it is of course your call whether to modernize syntax, and doing so in a major version bump as you did makes sense. I would just suggest updating the release notes and/or README to reflect this, as it is a breaking change.

**Comment by UziTech** [comment]
>  I would just suggest updating the release notes and/or README to reflect this, as it is a breaking change.

If you would like to help list every possible things that can break between each breaking change, that would be very helpful😁👍

**Comment by Bram-diederik** [comment]
Old browsers. this issue affects all Debian bookworm QT web browsers.
Are we disrespecting stability here?

**Comment by UziTech** [comment]
@Bram-diederik if you would like to release a marked package that is transpiled and polyfilled for browsers that do not support current standards, no one is stopping you. You will be getting paid twice as much as the marked team is. 😁👍

**Comment by smhg** [comment]
FWIW when using esbuild or vite, you'll get this error no matter what target you use (as it doesn't polyfill). `Array.prototype.at` requires a separate polyfill for pre-es2022 browsers (e.g. Safari 14).

One way to polyfill it is:
```bash
npm i array.prototype.at
```
```js
import at from 'array.prototype.at';
at.shim();
```

**Comment by Moruox** [comment]
推荐官方做个兼容判断,你们的使用者不止是框架的项目,原生项目没有Babel转义

**Comment by UziTech** [comment]
@Moruox this is an open source project, so anyone who want to can fork it to make a version that works with those environments. So far I don't know anyone who wants it bad enough to put in the work.
