### ISSUE TITLE
TypeError: this.renderer.html is not a function (Error in 0.8.1, OK in 0.8.0)

### ISSUE THREAD

**Issue by kozi** [markedjs/marked#1621]
**Describe the bug**

Bug in **0.8.1**. In version 0.8.0 everything works fine. 
 
```bash
(node:17048) UnhandledPromiseRejectionWarning: TypeError: this.renderer.html is not a function
Please report this to https://github.com/markedjs/marked.
    at InlineLexer.output (C:\Users\XYZ\workspace\node_modules\marked\src\InlineLexer.js:85:30)
    at Parser.tok (C:\Users\XYZ\workspace\node_modules\marked\src\Parser.js:97:36)
    at Parser.parse (C:\Users\XYZ\workspace\node_modules\marked\src\Parser.js:47:19)
    at Function.parse (C:\Users\XYZ\workspace\node_modules\marked\src\Parser.js:30:19)
    at marked (C:\Users\XYZ\workspace\node_modules\marked\src\marked.js:103:19)
```

**Comment by UziTech** [comment]
What markdown are you sending to marked?

**Comment by UziTech** [comment]
The easiest way for us to debug is to provide a link to a [demo](https://marked.js.org/demo/) that demonstrates the error.

**Comment by kozi** [comment]
This code leads to the error:
```markdown

## internal header <!-- internal -->

```


![Anmerkung 2020-03-20 120829](https://user-images.githubusercontent.com/464029/77158436-9d549100-6aa3-11ea-8a79-89eaee040b2d.png)

While this code for example works:
```markdown

* line one
* line two <!-- internal -->
* line three <!-- internal -->
* line four

```

**Comment by styfle** [comment]
Thanks! I confirmed this is a regression in 0.8.1 and works correctly in 0.8.0.

Any html comment in a heading causes the error, the simplest being `# <!---->`.
